name: Docker Image CI

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux
          #- windows # Too flaky
    steps:

      - name: Clone project
        uses: actions/checkout@v4

      - name: Build release
        run: docker build -f ci/Dockerfile.${{ matrix.target }} . -t kmonad-builder

      - name: Save binary
        run: |
          mkdir output
          docker run --rm -v ${PWD}/output:/host/ kmonad-builder bash -c 'cp -vp /output/* /host/'

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: kmonad-${{ matrix.target }}
          path: 'output/*'
